<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Midi_IO_2</RootNamespace>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
  </PropertyGroup>

	<PropertyGroup>
		<CsWinRTEnabled>false</CsWinRTEnabled>
		<Copyright>Copyright @  2025 - 2026  operatortwo</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.Devices.Midi2" Version="1.0.13-preview.13.192" />
  </ItemGroup>

</Project>
